# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

# Build version format
version: "{build}"

clone_depth: 10

# Fix line endings on Windows
init:
  - git config --global core.autocrlf true

# What combinations to test
environment:
  matrix:
    - nodejs_version: 0.10
    - nodejs_version: 0.12
    - nodejs_version: 1

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  - cmd: npm test
